name: Deploy to Amazon ECS

on:
  push:
    branches: [ "master" ]


env:
  AWS_REGION: us-east-1                          # ECR Public siempre usa us-east-1
  ECR_PUBLIC_REGISTRY_ALIAS: v1f7d2c1             # tu alias público en ECR
  ECR_REPOSITORY: expensespublic
  IMAGE_TAG: ${{ github.sha }}

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR Public
      run: |
        aws ecr-public get-login-password --region us-east-1 \
          | docker login --username AWS --password-stdin public.ecr.aws

    - name: Build, tag, and push image
      run: |
        IMAGE_URI=${{ secrets.MY_ECR_REPOSITORY }}:latest
        echo "Building $IMAGE_URI"
        docker build -t $IMAGE_URI .
        docker push $IMAGE_URI
    
